### ISSUE TITLE
Problem when install mmdet3d

### ISSUE THREAD

**Issue by Pixie8888** [SerCharles/CN-RMA#9]
Dear author, I followed your instruction to install mmdet3d. I installed pytorch1.11+cu11.3. When I run ```python setup.py develop``` to install mmdet3d, it gives this error: ```The detected CUDA version (12.5) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA versions.``` Do you know how to solve it?

**Comment by SerCharles** [comment]
Your cuda card may be too advanced(4090 for example)...

**Comment by Pixie8888** [comment]
Can your model be run on 24GB gpu?

**Comment by SerCharles** [comment]
no

**Comment by Pixie8888** [comment]
Thanks!
